### ISSUE TITLE
Dependency Version Mismatch: v1.0.0 bower.json references old version of handlebars dependency when package.json fixes references

### ISSUE THREAD

**Issue by tarunc** [components/ember#56]
See https://github.com/components/ember/blob/1.0.0/package.json#L9 and https://github.com/components/ember/blob/1.0.0/bower.json#L9 and
https://github.com/components/ember/blob/1.0.0/component.json#L11

In `bower.json` and `component.json`, they refer to handlebars#v1.0.0 when they should refer to `"handlebars": ">= 1.0.0 < 2.0.0"`

**Comment by williamsbdev** [comment]
@tarunc is this still an issue?
