### ISSUE TITLE
Ember runtime?

### ISSUE THREAD

**Issue by awkaiser** [components/ember#58]
It would be awesome if the versioned Bower packages for Ember included the runtime.

I'm also looking forward to this landing: https://github.com/emberjs/ember.js/pull/4595

:beers:

**Comment by williamsbdev** [comment]
@awkaiser it appears the PR you referenced has been merged. Can this be resolved?

**Comment by awkaiser** [comment]
@williamsbdev No. The built `ember-runtime.js` script is [available on the channel branches](https://github.com/components/ember/tree/beta), but not the [versioned tags](https://github.com/components/ember/tree/2.1.0-beta.3).
