### ISSUE TITLE
Render into 'application' raises error

### ISSUE THREAD

**Issue by donovan-graham** [components/ember#67]
I'm currently running ember#canary 1.12.0-beta.1+canary.f8321643 with htmlbars.  

When trying to insert an outlet into application it raises an error:
`Uncaught TypeError: Cannot read property 'routeName' of undefined`

Following a simple example from Ember cookbooks, here's the code I'm trying to use
http://emberjs.com/guides/cookbook/user_interface_and_interaction/using_modal_dialogs/

routes/application.js
```
export default Ember.Route.extend({
  actions: {
    openModal: function(template) {
      template = template || 'modal';
      return this.render(template, {
        into: 'application',
        outlet: 'modal'
      });
    }
});
```

templates/application.hbs
```
{{outlet}}
{{outlet 'modal'}}
<button {{action "openModal"}}>Open</button>
```

**Comment by williamsbdev** [comment]
@donovan-graham I believe if this is still an issue, you should open the issue https://github.com/emberjs/ember.js/issues.
