### ISSUE TITLE
[QUESTION]: when will the 1.11.2 version be available for ember-cli users?

### ISSUE THREAD

**Issue by williamsbdev** [components/ember#70]
There was a vulnerability fix for Ember with the fix version being 1.11.2. I am not currently able to bower install this version. Thanks!

**Comment by rwjblue** [comment]
It is in process, had to wait for all the travis builds.

**Comment by williamsbdev** [comment]
awesome! Thank you!

**Comment by rwjblue** [comment]
1.11.2 is released
