### ISSUE TITLE
Unusually large repo size when running git clone

### ISSUE THREAD

**Issue by jakedetels** [components/ember#75]
When running `git clone https://github.com/components/ember.git`, it appears the overall size of the repo is unusually large (1.31 GB) - see screenshot below.

![image](https://cloud.githubusercontent.com/assets/8092406/16200185/1461407e-36c1-11e6-900b-0e28e7a89f35.png)

I've found that there is one particular hidden file that is very large: `ember\.git\objects\pack\pack-8f0fcba433cb69171896f744812f9be0df425d12.pack`, which is 1.3  GB.  I'm not sure what this file is.  One of my colleagues validated that he gets the same results when attempting to clone this repo.

Additionally, prior to cloning this repo, I did a fresh install of git.  I have the latest version of git for Windows (see screenshot below).  I'm not clear whether this issue is related to: 1) this components/ember repo, 2) github, or 3) this version of git.

![image](https://cloud.githubusercontent.com/assets/8092406/16200609/e2dad39c-36c2-11e6-9eb7-4561e2e80123.png)

**Comment by alexhancock** [comment]
For what it is worth... I ran a `git gc --aggressive` on our copy of this repo, and it make the pack file go from 1.6gb to 100mb.

Someone who has control over this repo could do that for this remote copy.

**Comment by rwjblue** [comment]
Not sure how to tell GitHub's servers to run git gc...

**Comment by alexhancock** [comment]
So, one thing you can do is just to run...

git gc --aggressive

... on your own machine and then delete the repo and immediately re-create and push.

It's just an issue with the remote hosted by github.

**Comment by alexhancock** [comment]
That might create a situation where you'd lose all GitHub specific data (issues/stars and whatnot) though... We didn't have to think about this issue with our internal copy.

It may be a better idea to file a support ticket with GitHub.

**Comment by rwjblue** [comment]
I deleted a few larger branches, I believe that will resolve this...
