### ISSUE TITLE
README should be more clear on what this repo actually is.

### ISSUE THREAD

**Issue by choclaudio** [components/ember#76]
A shim for what? what is the purpose, what is the end goal, where is it being used currently etc.

**Comment by rwjblue** [comment]
It is the build output for emberjs/ember.js repo. When someone does `bower install ember` this is the repo that hits.

**Comment by choclaudio** [comment]
Ah, ok! Thank you for the information @rwjblue Maybe this is obvious for most emberinos, but it was  not obvious for me. If you think that a small clarification would be valuable in the README.MD then that would be cool, otherwise just close this issue. :beers:

**Comment by rwjblue** [comment]
Absolutely! A PR with clarification would absolutely be welcome.
