### ISSUE TITLE
Error while using EmberJS 2.8.0: view.parentView = null

### ISSUE THREAD

**Issue by josemariaruiz** [components/ember#77]
The code `view.parentView = null;` generates the error:

```ember.debug.js:6778 Uncaught Error: Assertion Failed: You must use Ember.set() to set the `parentView` property (of <spa@component:md-card-content::ember946>) to `null`.```

The code appears in `ember.js`.

**Comment by rwjblue** [comment]
We track Ember bugs in https://github.com/emberjs/ember.js/ repo (this is just for the built assets).

Looks like this is the same issue as https://github.com/emberjs/ember.js/issues/14266, lets track it over there.
